# Design Agent - Handles issues and creates design specifications
name: Design Agent

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to design'
        required: true
        type: string
      priority:
        description: 'Priority level (low, normal, high, urgent)'
        required: false
        default: 'normal'
        type: choice
        options:
          - 'low'
          - 'normal'
          - 'high'
          - 'urgent'

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  models: read
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write
  repository-projects: write



jobs:
  design:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Design Agent
        uses: ./
        with:
          task: |
            Analyze issue #${{ github.event.inputs.issue_number }}: 
            Priority: ${{ github.event.inputs.priority }}
            
            Your role: Solution Design Architect
            
            Tasks:
            1. Analyze the issue requirements thoroughly
            2. Create a comprehensive design specification
            3. Save the specification to specs/${{ github.event.inputs.issue_number }}-[issue-title].md
            4. Create a pull request with the design specification
            5. Add appropriate labels and assign reviewers
            
            Design specification should include:
            - Problem statement and requirements analysis
            - Proposed solution architecture
            - Technical implementation approach
            - Security and compliance considerations
            - Testing strategy
            - Risk assessment and mitigation
            - Resource requirements and timeline
            
            Issue Details:
            Issue Number: ${{ github.event.inputs.issue_number }}
            Priority: ${{ github.event.inputs.priority }}
            
            Note: Retrieve issue details using GitHub API to get title, body, labels, and author information.
          
          system_prompt: |
            You are a senior solution architect responsible for creating comprehensive design specifications.
            
            Your expertise includes:
            - Requirements analysis and stakeholder management
            - System architecture and design patterns
            - Security and compliance best practices
            - Risk assessment and mitigation strategies
            - Technical feasibility analysis
            
            Always consider:
            - Scalability and performance implications
            - Security vulnerabilities and mitigation
            - Maintainability and code quality
            - Integration with existing systems
            - Resource constraints and timeline feasibility
            
            Create specifications that are detailed enough for implementation
            but flexible enough to allow for technical creativity.
          
          tools: "file_read,file_write,use_github,add_comment,list_issues,current_time,think"
          
          provider: "bedrock"
          model: "us.anthropic.claude-sonnet-4-20250514-v1:0"
          max_tokens: "32768"
          
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
